version: "3.9"
services:
    db:
      container_name: db
      image: mcr.microsoft.com/mssql/server
      environment:
        - SA_PASSWORD=${DBPASS}
        - ACCEPT_EULA=Y
      ports:
        - "1433"
      network_mode: "host"