version: "3.9"
services:
    inventory:
      container_name: inventory
      build: 
        context: ../../
        dockerfile: microservices/${INVENTORY}/${INVENTORY}.Service/Dockerfile
        args:
          service: ${INVENTORY}
      image: inventory
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:8002;http://+:8003
        - ASPNETCORE_Kestrel__Certificates__Default__Password=DevCertPassword
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        - ConnectionStrings__DefaultConnection=Server=localhost;Database=${INVENTORY}.Service.Db;User ID=sa;Password=${DBPASS};TrustServerCertificate=true;
      ports:
        - "8002"
        - "8003"
      volumes:
        - ../../.local/https:/https:ro
      network_mode: "host"